/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientewebservicesad;

/**
 *
 * @author Cristian
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        horas = new javax.swing.JTextField();
        pago_hora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);
        jPanel1.add(horas);
        horas.setBounds(130, 60, 160, 30);
        jPanel1.add(pago_hora);
        pago_hora.setBounds(130, 110, 160, 30);

        jLabel4.setText("Horas: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 70, 80, 14);

        jLabel5.setText("Pago por hora");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 120, 80, 14);

        jLabel6.setText("El resultado es:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 210, 120, 14);
        jPanel1.add(resultado);
        resultado.setBounds(140, 210, 90, 14);

        jButton1.setText("Calcular total pago por horas en la semana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 160, 310, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 575, 331);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a, b;
        a = horas.getText();
        b = pago_hora.getText();
        
        try { // Call Web Service Operation
            uddi.ServicioCalculosPrueba_Service service = new uddi.ServicioCalculosPrueba_Service();
            uddi.ServicioCalculosPrueba port = service.getServicioCalculosPruebaPort();
            // TODO initialize WS operation arguments here
            double pagoHora = Double.parseDouble(a);
            double horasDia = Double.parseDouble(b);
            // TODO process result here
            double result = port.calculoHorasSueldo(pagoHora, horasDia);
            System.out.println("Result = "+result);
            resultado.setText(String.valueOf(result));
        } catch (Exception ex) {
            // TODO handle custom exceptions here
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField horas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pago_hora;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
